# Generated by Django 4.2 on 2023-04-17 08:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModels',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', unique=True)),
                ('password', models.CharField(db_column='password')),
                ('name', models.CharField(db_column='name')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('phone_number', models.CharField(db_column='phone_number')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
