# Generated by Django 4.2 on 2023-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModels',
            fields=[
                ('account_id', models.AutoField(db_column='account_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='user_name')),
                ('password', models.CharField(db_column='password')),
                ('name', models.CharField(db_column='name')),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('phone_number', models.CharField(db_column='phone_number')),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='update_date')),
            ],
        ),
    ]
