# Generated by Django 4.2 on 2023-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodels',
            name='salt_password',
            field=models.CharField(db_column='salt_password', default=None),
        ),
    ]
