# Generated by Django 4.2 on 2023-04-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodels_salt_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodels',
            name='salt_password',
        ),
    ]
