# Generated by Django 4.2 on 2023-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModels',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name')),
                ('category_parent_id', models.IntegerField(blank=True, db_column='category_parent_id', null=True)),
            ],
        ),
    ]
