# Generated by Django 4.2 on 2023-04-17 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModels',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='category_name', unique=True)),
                ('category_date_submit', models.DateTimeField(auto_now_add=True, db_column='category_date_submit')),
                ('category_date_updated', models.DateTimeField(auto_now=True, db_column='category_date_updated')),
                ('category_account_id', models.ForeignKey(db_column='category_account_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
