# Generated by Django 4.2 on 2023-04-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_delete_postmodels'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModels',
        ),
    ]
